env:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: "jdbc:postgresql://ref-db.database-dev-pg.cloud.vimpelcom.ru:5432/refs"
  SPRING_DATASOURCE_USERNAME: "vault:eafdmmart/data/dev/fdm#refs.db.user"
  SPRING_DATASOURCE_PASSWORD: "vault:eafdmmart/data/dev/fdm#refs.db.pass"


podAnnotations:
  vault.security.banzaicloud.io/vault-addr: "https://vault-test.vimpelcom.ru/"


ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-headers: Content-Type, authorization, Content-Disposition
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, PUT, DELETE, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-expose-headers: "Content-Disposition"
