name: Smoke test

# Запускать при создании/обновлении PR в main
on:
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Smoke test
      - name: Smoke test... Build and run via docker-compose
        run: |
          docker compose version || (echo "Docker Compose not found" && sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose)
          # Run compose
          docker compose -f docker-compose.yml up --wait --wait-timeout 120 -d
          mkdir -p logs
          docker compose logs > logs/compose.log.txt
          # Cleanup
          sleep 5
          docker compose -f docker-compose.yml down -v
      
      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: compose-logs
          path: logs/
